package id.ac.ui.cs.mobileprogramming.nathanael.pocketguideofcharacters.activities;

import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.view.KeyEvent;
import android.view.Menu;
import android.view.MenuItem;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;
import androidx.navigation.NavController;
import androidx.navigation.fragment.NavHostFragment;
import androidx.navigation.ui.AppBarConfiguration;
import androidx.navigation.ui.NavigationUI;

import com.google.android.material.bottomnavigation.BottomNavigationView;

import id.ac.ui.cs.mobileprogramming.nathanael.pocketguideofcharacters.R;

/**
 * Main and landing activity, using bottom navigation and several fragment.
 *
 * @author Nathanael
 */
public class LandingActivity extends AppCompatActivity {

    /**
     * Required attribute to override exit by pressing back button twice.
     * Ref: https://stackoverflow.com/a/20853151/13645004.
     */
    private boolean backPressedToExitOnce = false;

    /**
     * Required attribute to show toast when overriding exit by pressing back button twice.
     * Ref: https://stackoverflow.com/a/20853151/13645004.
     */
    private Toast toast = null;

    /**
     * @param savedInstanceState to pass to superclass
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_base_navigation);

        // Initiate navigation views and routing configuration
        // Generated by Android Studio
        BottomNavigationView navView = findViewById(R.id.nav_view);
        AppBarConfiguration appBarConfiguration = new AppBarConfiguration.Builder(
                R.id.navigation_home,
                R.id.navigation_dashboard
        )
                .build();
        NavHostFragment navHostFragment = (NavHostFragment) getSupportFragmentManager().findFragmentById(R.id.nav_host_fragment);
        assert navHostFragment != null;
        NavController navController = navHostFragment.getNavController();
        NavigationUI.setupActionBarWithNavController(this, navController, appBarConfiguration);
        NavigationUI.setupWithNavController(navView, navController);
    }

    // create an action bar button
    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.custom_timer_menu, menu);
        return super.onCreateOptionsMenu(menu);
    }

    // handle button activities
    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        int id = item.getItemId();

        if (id == R.id.timerModeButton) {
            startActivity(
                    new Intent(LandingActivity.this, TimerActivity.class)
            );
        }
        return super.onOptionsItemSelected(item);
    }

    /**
     * Alternative to OnBackButtonPressed that does not work without explored reason.
     *
     * @param keyCode pressed key
     * @param event   to pass to superclass
     * @return superclass return value. true if default back allowed, false otherwise.
     */
    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        // check back key pressed
        if (keyCode == KeyEvent.KEYCODE_BACK) {

            if (findViewById(R.id.nameField) != null) {
                // name field visible on current activity means current active fragment is Create

                // automatically go press the home navigation
                findViewById(R.id.navigation_home).performClick();

                // do not return default back, it will break the home fragment.
                return false;
            } else if (!backPressedToExitOnce) {

                // require user to press back button twice in 2000ms to exit;
                this.backPressedToExitOnce = true;

                // show toast
                showToast("Press again to exit");

                // start 2000ms counter
                new Handler().postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        backPressedToExitOnce = false;
                    }
                }, 2000);

                return false;
            }
        }
        return super.onKeyDown(keyCode, event);
    }

    /**
     * Created to make sure that you toast doesn't show multiple times, if user pressed back
     * button more than once. Ref: https://stackoverflow.com/a/20853151/13645004.
     *
     * @param message Message to show on toast.
     */
    private void showToast(String message) {
        if (this.toast == null) this.toast = Toast.makeText(this, message, Toast.LENGTH_SHORT);
        else if (this.toast.getView() == null)
            this.toast = Toast.makeText(this, message, Toast.LENGTH_SHORT);
        else this.toast.setText(message);
        this.toast.show();
    }

    /**
     * Kill the toast if showing. Supposed to call from onPause() of activity.
     * So that toast also get removed as activity goes to background, to improve
     * better app experience for user. Ref: https://stackoverflow.com/a/20853151/13645004.
     */
    private void killToast() {
        if (this.toast != null) {
            this.toast.cancel();
        }
    }

    /**
     * Override on pause to kill toast before pausing.
     */
    @Override
    protected void onPause() {
        killToast();
        super.onPause();
    }
}
